/*
 * This source file was generated by the Gradle 'init' task
 */
package net.charukak.sudoku.launcher;

public class App {

    public static void main(String[] args) {
        GameLoop gl = new GameLoop();
        gl.Run();
    }
}
